name: Azure Final Static Web Apps CI/CD

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:    
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
  
      - name: Install dependencies and build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn install
          yarn build    
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_COAST_0D78FB010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"         
          app_location: "build" # App source code path
          skip_app_build: true

  
