name: Build and deploy Node.js app to Azure Web App - hporveniruiapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies and build
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn install
        yarn build

    - name: Deploy to Azure Web App
      uses: azure/static-web-apps-deploy@v1
      with:
        app-name: 'hporveniruiapp'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ad6582842c504eb6818f209b36e142b2 }}
        package: ./build
