name: Build and deploy ui

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies and build
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        npm install -g yarn --force
        yarn install
        CI='' yarn run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hporveniruiapp'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ad6582842c504eb6818f209b36e142b2 }}
        package: build
